---
- name: Pull docker image of Calculator.Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull sarika476/scientific_calculator
